[package]
name = "grrs"
version = "0.1.0"
authors = ["Matthew Blode <m@blode.co>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
failure = "0.1.5"
exitfailure = "0.5.1"
indicatif = "0.11.0"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
